# Generated by Django 5.0.6 on 2024-06-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_user', '0003_friend_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('from_user', 'to_user')},
        ),
    ]
