# Generated by Django 5.0.6 on 2024-07-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_user', '0004_alter_user_id_alter_friendrequest_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('P', 'Pending')], default='P', max_length=10),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
